name: Build master

on:
  push:
    paths-ignore:
      - 'papers/**'
      # do not run CI if we are writing a paper
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-ignoring-paths
    branches:
      #- 'master'
      - 'LOPSTR-2023'

jobs:
  build:
    env:
      OPAMROOT: /home/user/.opam

    runs-on: ubuntu-latest
    container:
      image: kakadu18/ocaml:pltlab
      options: --user user

    steps:
      - run: opam --version
      - run: opam exec -- ocamlopt --version
      - run: opam update

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true


      - run: opam install ./src --yes --deps-only --with-test --with-doc

      - name: List installed dependencies...
        run: opam list

      - run: opam exec -- dune test --profile=release
        working-directory: ./src
